comment_width = 80
imports_granularity = "Module"
imports_layout = "Horizontal"
force_multiline_blocks = true
format_code_in_doc_comments = true
max_width = 80
normalize_comments = true
tab_spaces = 2
wrap_comments = true
